# Generated by Django 2.2.3 on 2019-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=20)),
                ('modele', models.CharField(max_length=200)),
                ('annee', models.IntegerField()),
                ('cylendre', models.IntegerField()),
                ('puissance', models.IntegerField()),
                ('couleur', models.CharField(max_length=20)),
                ('boite', models.CharField(max_length=20)),
            ],
        ),
    ]
