# Generated by Django 2.2.3 on 2019-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20190723_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstable',
            name='img',
            field=models.CharField(default='image ici !!', max_length=300),
            preserve_default=False,
        ),
    ]
