# Generated by Django 2.2.2 on 2019-07-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_auto_20190723_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carstable',
            name='boite',
        ),
        migrations.RemoveField(
            model_name='carstable',
            name='cylindre',
        ),
        migrations.RemoveField(
            model_name='carstable',
            name='puissance',
        ),
        migrations.CreateModel(
            name='Fich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylindre', models.IntegerField()),
                ('puissance', models.IntegerField()),
                ('boite', models.BooleanField(default=True)),
                ('desc', models.CharField(max_length=500)),
                ('energie', models.CharField(max_length=100)),
                ('nb_place', models.IntegerField()),
                ('nb_door', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.CarsTable')),
            ],
        ),
    ]
