# Generated by Django 2.2.2 on 2019-07-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20190724_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fich',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fich', to='marketplace.CarsTable'),
        ),
    ]
