# Generated by Django 2.2.2 on 2019-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20190724_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='carstable',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
