# Generated by Django 2.2.2 on 2019-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_accessoirtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessoirtable',
            name='img_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carstable',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
