# Generated by Django 2.2.2 on 2019-07-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_auto_20190726_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessoirTable',
            new_name='EquipementTable',
        ),
    ]
