# Generated by Django 2.2.2 on 2019-07-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_auto_20190726_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoiresTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('img_urle', models.CharField(max_length=500)),
                ('prix', models.FloatField(default=0)),
            ],
        ),
    ]
